CLI- Instructions and aws provider fix
OpenMined/PyGrid pull request #737
Opened 2020-10-08 11:02 UTC by Nilanshrajput

## Description
Fix for a bug in CLI AWS Provider and updated instruction for deployment using CLI.
Added Terraform installation instructions in readme

## Affected Dependencies
None

## How has this been tested?
Not tested
## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2020-10-08 11:03 UTC, Nilanshrajput commented
@AmrMKayid  can you review this.

2020-10-08 11:05 UTC, Nilanshrajput commented
@AmrMKayid  also it seems like deployment using CLI is not tested as of now,  I am facing some issues deploying on AWS using cli other than this minor bug.

2020-10-12 01:35 UTC, IonesioJunior commented
@AmrMKayid , @sachin-101 Could you guys check this? :)

2020-10-14 15:39 UTC, AmrMKayid requested changes
Thanks for the PR and fixes, please check my comments and update the minor changes. :)

2020-10-14 15:39 UTC, AmrMKayid commented on README.md
> +Check Instructions here : https://learn.hashicorp.com/tutorials/terraform/install-cli#:~:text=If%20you%20get%20an%20error,directory%20where%20Terraform%20was%20installed.
Can you replace it with this link please: 
https://learn.hashicorp.com/tutorials/terraform/install-cli
```suggestion
Check Instructions here: https://learn.hashicorp.com/tutorials/terraform/install-cli
```

2020-10-14 15:39 UTC, AmrMKayid commented on README.md
> +#### Run Terraform init : terraform init
No need for `terraform init` since the CLI already do that once it received the inputs from the user

2020-10-16 14:10 UTC, AmrMKayid requested changes

2020-10-16 14:10 UTC, AmrMKayid commented on apps/cli/providers/aws.py
> +        return [region["RegionName"] for region self.client.describe_regions()["Regions"]]
there is a missing `in` here
```suggestion
        return [region["RegionName"] for region in self.client.describe_regions()["Regions"]]
```

2020-10-16 18:37 UTC, AmrMKayid approved these changes
LGTM! Thanks @Nilanshrajput for the fixes!

2020-10-17 09:07 UTC, merged